"""Versioned contracts for Open-Meteo ingestion."""

from vn_climate_risk_monitor.ingestion.open_meteo.archive_parser import (
    ARCHIVE_HOURLY_SCHEMA,
    ARCHIVE_PARSER_VERSION,
    ArchiveParseError,
    ArchiveParseResult,
    parse_archive_hourly,
)
from vn_climate_risk_monitor.ingestion.open_meteo.archive_planner import (
    ARCHIVE_AVAILABILITY_LAG_DAYS,
    DEFAULT_ARCHIVE_START_YEAR,
    ArchiveBackfillPlan,
    ArchiveMonthWindow,
    ArchiveRequestTask,
    ArchiveYearPlan,
    latest_complete_archive_date,
    plan_archive_backfill,
    plan_archive_year,
)
from vn_climate_risk_monitor.ingestion.open_meteo.contracts import (
    ARCHIVE_DATASET,
    ARCHIVE_HOURLY_VARIABLES,
    COLLECTOR_VERSION,
    FORECAST_DATASET,
    FORECAST_HOURLY_VARIABLES,
    REQUEST_CONTRACT_VERSION,
    SOURCE_NAME,
    ArchiveFileParameters,
    ArchiveRequestContract,
    ArchiveRunParameters,
    ForecastFileParameters,
    ForecastRequestContract,
    ForecastRunParameters,
    RequestedLocation,
    split_location_batches,
)
from vn_climate_risk_monitor.ingestion.open_meteo.parser import (
    FORECAST_HOURLY_SCHEMA,
    PARSER_VERSION,
    ForecastParseError,
    ForecastParseResult,
    parse_forecast_hourly,
)
from vn_climate_risk_monitor.storage.models import SourceObjectMetadata

__all__ = [
    "ARCHIVE_AVAILABILITY_LAG_DAYS",
    "ARCHIVE_DATASET",
    "ARCHIVE_HOURLY_SCHEMA",
    "ARCHIVE_HOURLY_VARIABLES",
    "ARCHIVE_PARSER_VERSION",
    "COLLECTOR_VERSION",
    "DEFAULT_ARCHIVE_START_YEAR",
    "FORECAST_DATASET",
    "FORECAST_HOURLY_SCHEMA",
    "FORECAST_HOURLY_VARIABLES",
    "PARSER_VERSION",
    "REQUEST_CONTRACT_VERSION",
    "SOURCE_NAME",
    "ArchiveBackfillPlan",
    "ArchiveFileParameters",
    "ArchiveMonthWindow",
    "ArchiveParseError",
    "ArchiveParseResult",
    "ArchiveRequestContract",
    "ArchiveRequestTask",
    "ArchiveRunParameters",
    "ArchiveYearPlan",
    "ForecastFileParameters",
    "ForecastParseError",
    "ForecastParseResult",
    "ForecastRequestContract",
    "ForecastRunParameters",
    "RequestedLocation",
    "SourceObjectMetadata",
    "latest_complete_archive_date",
    "parse_archive_hourly",
    "parse_forecast_hourly",
    "plan_archive_backfill",
    "plan_archive_year",
    "split_location_batches",
]
